const both = true && false;
const either = true || false;
const fallback = null ?? 'default';
const negated = !true;
const ternary = 5 > 3 ? 'yes' : 'no';
console.log(both);
console.log(either);
console.log(fallback);
console.log(negated);
console.log(ternary);
