const pi = Math.PI;
const rounded = Math.round(3.7);
const floored = Math.floor(3.7);
const ceiled = Math.ceil(3.2);
const truncated = Math.trunc(3.7);
const absolute = Math.abs(-7);
const root = Math.sqrt(16);
const power = Math.pow(2, 3);
const bigger = Math.max(3, 7);
const smaller = Math.min(3, 7);
const rand = Math.random();
console.log(pi);
console.log(rounded);
console.log(floored);
console.log(ceiled);
console.log(truncated);
console.log(absolute);
console.log(root);
console.log(power);
console.log(bigger);
console.log(smaller);
console.log(rand);
