let pi = Math.PI;
let rounded = Math.round(3.7);
let floored = Math.floor(3.7);
let ceiled = Math.ceil(3.2);
let truncated = Math.trunc(3.7);
let absolute = Math.abs(-7);
let root = Math.sqrt(16);
let power = Math.pow(2, 3);
let bigger = Math.max(3, 7);
let smaller = Math.min(3, 7);
let rand = Math.random();
console.log(pi);
console.log(rounded);
console.log(floored);
console.log(ceiled);
console.log(truncated);
console.log(absolute);
console.log(root);
console.log(power);
console.log(bigger);
console.log(smaller);
console.log(rand);
